name: Workflow for UI

on:
  push:
    branches: ["main"]
    paths: ["front/**"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "aws"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.KWIK_AGENT_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.KWIK_AGENT_AWS_ACCESS_KEY_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
      
      - name: Install dependencies
        run: npm install
        
      - name: Build project
        run: npm run build

      - name: Deploy to AWS
        uses: reggionick/s3-deploy@v4
        with:
          folder: dist
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          bucket-region: ${{ secrets.AWS_S3_REGION }}
          dist-id: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: /
          delete-removed: true
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'
